package main

// Rendering mediamtx.yml from the config.
//
// The file is written whole, every time, from Config — never edited in place —
// so what MediaMTX runs is always exactly what the tab shows. Only the keys
// this gateway uses are emitted; everything else takes MediaMTX's default,
// which keeps the rendered file readable and the diff between two versions
// meaningful.
//
// The key names are MediaMTX's own and change between releases. The version
// they were written against is pinned below and checked in CI by running the
// real binary's --validate-conf over the rendered fixtures; bump both together.

import (
	"fmt"
	"strings"
)

// MediaMTXVersion is the release the rendered file is known to validate
// against. The patcher pins the same version when it fetches the binary.
const MediaMTXVersion = "v1.21.0"

// yq renders a YAML double-quoted scalar. Validation has already refused
// control characters and quotes in anything user-supplied, so this is belt
// and braces rather than the only defence.
func yq(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			b.WriteString(`\"`)
		case '\\':
			b.WriteString(`\\`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			if r < 0x20 {
				fmt.Fprintf(&b, `\x%02x`, r)
			} else {
				b.WriteRune(r)
			}
		}
	}
	b.WriteByte('"')
	return b.String()
}

// yblock renders a multi-line string as a literal block scalar at the given
// indent, for the SDP.
func yblock(s string, indent string) string {
	var b strings.Builder
	b.WriteString("|\n")
	for _, line := range strings.Split(strings.TrimRight(s, "\n"), "\n") {
		b.WriteString(indent)
		b.WriteString(strings.TrimRight(line, "\r"))
		b.WriteByte('\n')
	}
	return b.String()
}

// Render produces the complete mediamtx.yml for c.
func Render(c Config) string {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }

	w("# Generated by bdgw from config.json — do not edit, use the Streaming tab.\n")
	w("# Written for MediaMTX %s.\n", MediaMTXVersion)
	w("logLevel: info\n")
	w("logDestinations: [stdout]\n")
	w("readTimeout: 10s\n")
	w("writeTimeout: 10s\n")
	w("\n")
	w("# The control API is how the panel reads status. Loopback only.\n")
	w("api: yes\n")
	w("apiAddress: 127.0.0.1:%d\n", PortAPI)
	w("metrics: no\n")
	w("pprof: no\n")
	w("playback: no\n")
	w("\n")
	w("# No credentials: like the PLAY's own API on :8080, the LAN or the tailnet\n")
	w("# is the boundary. See the README before exposing the box.\n")
	w("authMethod: internal\n")
	w("authInternalUsers:\n")
	w("  - user: any\n")
	w("    pass:\n")
	w("    ips: []\n")
	w("    permissions:\n")
	w("      - action: publish\n")
	w("      - action: read\n")
	w("  - user: any\n")
	w("    pass:\n")
	w("    ips: [\"127.0.0.1\", \"::1\"]\n")
	w("    permissions:\n")
	w("      - action: api\n")
	w("\n")
	w("rtsp: yes\n")
	w("rtspAddress: :%d\n", PortRTSP)
	w("rtspTransports: [udp, multicast, tcp]\n")
	w("rtspEncryption: \"no\"\n")
	w("rtmp: yes\n")
	w("rtmpAddress: :%d\n", PortRTMP)
	w("rtmpEncryption: \"no\"\n")
	w("hls: yes\n")
	w("hlsAddress: :%d\n", PortHLS)
	w("hlsAlwaysRemux: no\n")
	w("webrtc: yes\n")
	w("webrtcAddress: :%d\n", PortWebRTC)
	w("srt: yes\n")
	w("srtAddress: :%d\n", PortSRT)
	w("# Media-over-QUIC is not exposed: one more listener nobody on a PLAY has asked for.\n")
	w("moq: no\n")
	w("\n")
	w("pathDefaults:\n")
	w("  source: publisher\n")
	w("  sourceOnDemand: no\n")
	w("  overridePublisher: yes\n")
	w("\n")
	w("paths:\n")
	if len(c.Paths) == 0 {
		w("  {}\n")
	}
	for _, p := range c.Paths {
		w("  %s:\n", p.Name)
		if p.Label != "" {
			w("    # %s\n", strings.ReplaceAll(strings.TrimSpace(p.Label), "\n", " "))
		}
		if p.IsPublish() {
			w("    source: publisher\n")
		} else {
			w("    source: %s\n", yq(strings.TrimSpace(p.Source)))
			if p.OnDemand {
				w("    sourceOnDemand: yes\n")
			}
			if strings.HasPrefix(strings.ToLower(strings.TrimSpace(p.Source)), "udp+rtp://") && p.SDP != "" {
				w("    rtpSDP: %s", yblock(p.SDP, "      "))
			}
		}
		if p.HoldPicture {
			w("    alwaysAvailable: yes\n")
			w("    alwaysAvailableTracks:\n")
			w("      - codec: H264\n")
		}
		if len(p.Forward) > 0 {
			w("    forward:\n")
			for _, f := range p.Forward {
				w("      - dest: %s\n", yq(strings.TrimSpace(f.URL)))
				if f.Fingerprint != "" {
					w("        destFingerprint: %s\n", yq(strings.ToLower(strings.ReplaceAll(f.Fingerprint, ":", ""))))
				}
			}
		}
	}
	return b.String()
}

// DecoderURI is the SRT connection string the PLAY's decoder is given for a
// path: the same shape the stock AV Setup form builds for a caller with no
// encryption, pointed at the hub on loopback.
func DecoderURI(path string, latencyMS int) string {
	return fmt.Sprintf("127.0.0.1:%d?mode=caller&latency=%d&streamid=read:%s", PortSRT, latencyMS, path)
}

// Endpoints lists, for the tab, the addresses a path is reachable at from the
// LAN. host is the device's own address as the browser sees it.
type Endpoints struct {
	PublishRTMP string `json:"publish_rtmp"`
	PublishRTSP string `json:"publish_rtsp"`
	PublishSRT  string `json:"publish_srt"`
	PublishWHIP string `json:"publish_whip"`
	ReadRTSP    string `json:"read_rtsp"`
	ReadRTMP    string `json:"read_rtmp"`
	ReadHLS     string `json:"read_hls"`
	ReadWebRTC  string `json:"read_webrtc"`
	ReadSRT     string `json:"read_srt"`
}

func EndpointsFor(host, path string) Endpoints {
	return Endpoints{
		PublishRTMP: fmt.Sprintf("rtmp://%s:%d/%s", host, PortRTMP, path),
		PublishRTSP: fmt.Sprintf("rtsp://%s:%d/%s", host, PortRTSP, path),
		PublishSRT:  fmt.Sprintf("srt://%s:%d?streamid=publish:%s&pkt_size=1316", host, PortSRT, path),
		PublishWHIP: fmt.Sprintf("http://%s:%d/%s/whip", host, PortWebRTC, path),
		ReadRTSP:    fmt.Sprintf("rtsp://%s:%d/%s", host, PortRTSP, path),
		ReadRTMP:    fmt.Sprintf("rtmp://%s:%d/%s", host, PortRTMP, path),
		ReadHLS:     fmt.Sprintf("http://%s:%d/%s", host, PortHLS, path),
		ReadWebRTC:  fmt.Sprintf("http://%s:%d/%s", host, PortWebRTC, path),
		ReadSRT:     fmt.Sprintf("srt://%s:%d?streamid=read:%s", host, PortSRT, path),
	}
}

// CameraPublishURL is what bdcam's SRT output should be set to.
func CameraPublishURL(path string) string {
	return fmt.Sprintf("srt://127.0.0.1:%d?streamid=publish:%s&pkt_size=1316", PortSRT, path)
}
